ALTER TABLE INVOICES ADD COLUMN CLIENT_COMPANY_NAME VARCHAR(255);
ALTER TABLE INVOICES ADD COLUMN CLIENT_EMAIL VARCHAR(255);
ALTER TABLE INVOICES ADD COLUMN CLIENT_NCC VARCHAR(255);
ALTER TABLE INVOICES ADD COLUMN CLIENT_PHONE VARCHAR(255);
ALTER TABLE INVOICES ADD COLUMN ESTABLISHMENT VARCHAR(255);
ALTER TABLE INVOICES ADD COLUMN POINT_OF_SALE VARCHAR(255);
ALTER TABLE INVOICES ADD COLUMN COMMERCIAL_MESSAGE VARCHAR(255);
ALTER TABLE INVOICES ADD COLUMN TOTAL_DISCOUNT DECIMAL(19,2);