CREATE TABLE IF NOT EXISTS seller_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tax_id VARCHAR(32) NOT NULL UNIQUE,
    company_name VARCHAR(255),
    logo_path VARCHAR(1024),
    logo_mime_type VARCHAR(100),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_seller_profiles_tax_id
    ON seller_profiles (tax_id);
