-- V9__multi_tenant_architecture.sql (H2)

-- ============================================================
-- 1) Tenants
-- ============================================================
CREATE TABLE tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    company_name VARCHAR(255) NOT NULL,
    ncc VARCHAR(20) NOT NULL UNIQUE,
    slug VARCHAR(100) NOT NULL UNIQUE,

    fne_api_key VARCHAR(500),
    fne_establishment VARCHAR(255) DEFAULT 'Siège',
    fne_point_of_sale VARCHAR(255) DEFAULT 'Caisse 1',

    subscription_plan VARCHAR(50) NOT NULL DEFAULT 'starter',
    subscription_status VARCHAR(50) NOT NULL DEFAULT 'trial',
    subscription_started_at TIMESTAMP,
    subscription_ends_at TIMESTAMP,

    monthly_invoice_limit INTEGER DEFAULT 50,
    monthly_invoice_count INTEGER DEFAULT 0,

    owner_email VARCHAR(255) NOT NULL UNIQUE,
    owner_name VARCHAR(255) NOT NULL,
    owner_phone VARCHAR(20),

    logo_url VARCHAR(500),

    is_active BOOLEAN DEFAULT TRUE,
    is_verified BOOLEAN DEFAULT FALSE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    created_by VARCHAR(255),
    last_login_at TIMESTAMP
);

CREATE INDEX idx_tenants_ncc ON tenants(ncc);
CREATE INDEX idx_tenants_slug ON tenants(slug);
CREATE INDEX idx_tenants_status ON tenants(subscription_status);

-- ============================================================
-- 2) Ajouter tenant_id aux tables existantes
-- ============================================================
ALTER TABLE invoices ADD COLUMN tenant_id BIGINT;
ALTER TABLE invoices
  ADD CONSTRAINT fk_invoices_tenant
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
CREATE INDEX idx_invoices_tenant ON invoices(tenant_id);

ALTER TABLE invoice_lines ADD COLUMN tenant_id BIGINT;
ALTER TABLE invoice_lines
  ADD CONSTRAINT fk_invoice_lines_tenant
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
CREATE INDEX idx_invoice_lines_tenant ON invoice_lines(tenant_id);

ALTER TABLE seller_profiles ADD COLUMN tenant_id BIGINT;
ALTER TABLE seller_profiles
  ADD CONSTRAINT fk_seller_profiles_tenant
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
CREATE INDEX idx_seller_profiles_tenant ON seller_profiles(tenant_id);

-- ============================================================
-- 3) Utilisateurs (multi-tenant)
-- ============================================================
CREATE TABLE tenant_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'user',
    is_active BOOLEAN DEFAULT TRUE,
    email_verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMP,
    CONSTRAINT fk_tenant_users_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
    CONSTRAINT uq_tenant_users UNIQUE(tenant_id, email)
);

CREATE INDEX idx_tenant_users_tenant ON tenant_users(tenant_id);
CREATE INDEX idx_tenant_users_email ON tenant_users(email);

-- ============================================================
-- 4) Plans d'abonnement
-- ============================================================
CREATE TABLE subscription_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    display_name VARCHAR(255) NOT NULL,
    monthly_price DECIMAL(10,2) NOT NULL,
    invoice_limit INTEGER NOT NULL,
    user_limit INTEGER NOT NULL,
    features JSON,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO subscription_plans (name, display_name, monthly_price, invoice_limit, user_limit, features) VALUES
('starter', 'Starter', 25000, 50, 1, '{"api_access": false, "priority_support": false, "custom_branding": false}'),
('professional', 'Professional', 50000, 500, 3, '{"api_access": true, "priority_support": true, "custom_branding": false}'),
('enterprise', 'Enterprise', 150000, 999999, 999, '{"api_access": true, "priority_support": true, "custom_branding": true, "dedicated_support": true}');

-- ============================================================
-- 5) Paiements
-- ============================================================
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    currency VARCHAR(10) DEFAULT 'XOF',
    payment_method VARCHAR(50),
    transaction_id VARCHAR(255),
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    paid_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payments_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

CREATE INDEX idx_payments_tenant ON payments(tenant_id);
CREATE INDEX idx_payments_status ON payments(status);

-- ============================================================
-- 6) Tenant admin + backfill
-- ============================================================
INSERT INTO tenants (
    company_name, ncc, slug,
    subscription_plan, subscription_status,
    monthly_invoice_limit,
    owner_email, owner_name,
    is_active, is_verified
) VALUES (
    'OXALIO SARL',
    '2505842N',
    'oxalio-admin',
    'enterprise',
    'active',
    999999,
    'admin@oxalio.ci',
    'Admin OXALIO',
    TRUE,
    TRUE
);

UPDATE invoices
SET tenant_id = (SELECT id FROM tenants WHERE slug = 'oxalio-admin')
WHERE tenant_id IS NULL;

UPDATE invoice_lines
SET tenant_id = (SELECT id FROM tenants WHERE slug = 'oxalio-admin')
WHERE tenant_id IS NULL;

UPDATE seller_profiles
SET tenant_id = (SELECT id FROM tenants WHERE slug = 'oxalio-admin')
WHERE tenant_id IS NULL;
