apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: pgdata, namespace: oxalio }
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources: { requests: { storage: 5Gi } }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: postgres, namespace: oxalio }
spec:
  replicas: 1
  selector: { matchLabels: { app: postgres } }
  template:
    metadata: { labels: { app: postgres } }
    spec:
      containers:
        - name: db
          image: postgres:15
          env:
            - { name: POSTGRES_PASSWORD, value: change_me }
          ports: [ { containerPort: 5432 } ]
          volumeMounts:
            - { name: data, mountPath: /var/lib/postgresql/data }
      volumes:
        - name: data
          persistentVolumeClaim: { claimName: pgdata }
---
apiVersion: v1
kind: Service
metadata: { name: postgres, namespace: oxalio }
spec:
  selector: { app: postgres }
  ports:
    - port: 5432
      targetPort: 5432
