spring:
  config:
    activate:
      on-profile: demo

  cloud:
    gateway:
      routes:
        - id: demo-invoice
          uri: https://httpbin.org/anything
          predicates:
            - Path=/api/v1/invoices/**
          filters:
            - StripPrefix=2

        - id: demo-auth
          uri: https://httpbin.org/anything
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2

        - id: demo-integration
          uri: https://httpbin.org/anything
          predicates:
            - Path=/api/v1/integration/**
          filters:
            - StripPrefix=2
