spring:
  config:
    activate:
      on-profile: prod

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2

        - id: invoice-service
          uri: http://invoice-service:8082
          predicates:
            - Path=/api/v1/invoices/**
          filters:
            - StripPrefix=2

        - id: integration-service
          uri: http://integration-service:8083
          predicates:
            - Path=/api/v1/integration/**
          filters:
            - StripPrefix=2
