CREATE TABLE invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number VARCHAR(255) NOT NULL UNIQUE,
    invoice_type VARCHAR(100) NOT NULL,
    currency VARCHAR(50) NOT NULL,
    issue_date TIMESTAMP NOT NULL,

    -- Seller
    seller_tax_id VARCHAR(100),
    seller_company_name VARCHAR(255),
    seller_address VARCHAR(255),

    -- Buyer
    buyer_tax_id VARCHAR(100),
    buyer_name VARCHAR(255),
    buyer_address VARCHAR(255),

    -- Totals
    subtotal DECIMAL(19, 2),
    total_vat DECIMAL(19, 2),
    total_amount DECIMAL(19, 2),

    -- Payment & QR
    payment_mode VARCHAR(100),
    sticker_id VARCHAR(100),
    qr_base64 CLOB,
    status VARCHAR(50),

    -- ✅ Champs DGI
    dgi_reference VARCHAR(255),
    dgi_submitted_at TIMESTAMP
);
